apiVersion: v1
kind: Pod
metadata:
  name: employeecrud-pod
  labels:
    app: employeecrud
spec:
  containers:
    - name: service
      image: goemployee_crud:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      env:
        - name: SERVER_PORT
          value: "8000"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres_user"
        - name: DB_PASSWORD
          value: "userspw"
        - name: DB_NAME
          value: "users_db"

# kubectl apply -f k8s/pod.yaml

